sudo: false

env:
  global:
    - BASELINE="SWTDemo"
    - BASELINE_GROUP="TravisCI"
    - PACKAGES="packages"
  matrix:
    - SMALLTALK="Squeak-Trunk"
    - SMALLTALK="Squeak-5.0"
    - SMALLTALK="Squeak-4.6"
    - SMALLTALK="Squeak-4.5"

    - SMALLTALK="Pharo-alpha"
    - SMALLTALK="Pharo-stable"
    - SMALLTALK="Pharo-5.0"
    - SMALLTALK="Pharo-4.0"
    - SMALLTALK="Pharo-3.0"

os:
  - linux
  - osx

addons:
  apt:
    packages:
    # 32-bit VM
    - libc6:i386
    # UUIDPlugin
    - libuuid1:i386
    # libFT2Plugin
    - libfreetype6:i386

install:
   - export PROJECT_HOME="$(pwd)"
   - cd $HOME
   - wget -q -O smalltalkCI.zip https://github.com/hpi-swa/smalltalkCI/archive/dev.zip
   - unzip -q smalltalkCI.zip
   - cd smalltalkCI-*
   - source env_vars

script: $SMALLTALK_CI_HOME/run.sh